name: Notify Discord of Changes

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "📢 A new change has been pushed to the bot repository! Check it out: https://github.com/KpnWorld/onWhisper-Bot/commits/main"}' \
          "$DISCORD_WEBHOOK"
