name: Discord Notify on Push

on:
  push:
    branches:
      - main  # This will trigger the action on pushes to the main branch.

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Send Discord notification
      run: |
        curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"A change has been pushed to the bot on GitHub!\"}" ${{ secrets.DISCORD_WEBHOOK }}
